name: CI
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  tests:
    name: "Tests"
    strategy:
      fail-fast: false
      matrix:
        group:
          - Core
          - Datafit
        version:
          - '1'
    uses: "SciML/.github/.github/workflows/tests.yml@v1"
    with:
      julia-version: "${{ matrix.version }}"
      group: "${{ matrix.group }}"
    secrets: "inherit"
